### ISSUE TITLE
Unlisted dependency on python-dateutil>=2.8.1 in woodwork 0.16.0

### ISSUE THREAD

**Issue by rwedge** [alteryx/woodwork#1393]
Woodwork imports `ParserError` from python-dateutil but `ParserError` was introduced in python-dateutil 2.8.1 while pandas 1.3.x requires python-dateutil>=2.7.3

pandas 1.4.x requires python-dateutil>=2.8.1

Introduced by #1365

Before python-dateutil 2.8.1 the same errors were ValueError, see https://github.com/dateutil/dateutil/pull/881

**Comment by rwedge** [comment]
To reproduce:

In clean python environment: 

`pip install woodwork==0.16.1 pandas<1.4 python-datutile<2.8`

```python-traceback
import woodwork as ww
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/woodwork/__init__.py", line 7, in <module>
    from .type_sys import type_system
  File "/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/woodwork/type_sys/__init__.py", line 1, in <module>
    from .type_system import type_system
  File "/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/woodwork/type_sys/type_system.py", line 3, in <module>
    from .inference_functions import (
  File "/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/woodwork/type_sys/inference_functions.py", line 10, in <module>
    from woodwork.type_sys.utils import _is_categorical_series, col_is_datetime
  File "/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/woodwork/type_sys/utils.py", line 2, in <module>
    from dateutil.parser import ParserError
ImportError: cannot import name 'ParserError' from 'dateutil.parser' (/Users/roy.wedge/opt/miniconda3/envs/testww/lib/python3.8/site-packages/dateutil/parser/__init__.py)
